name: tritek_lms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  bubble: ^1.1.9+1
  camera: ^0.8.1+5
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: any
  data_connection_checker: ^0.3.4
  dio: ^4.0.0
  email_validator: ^2.0.1
  floor: ^1.1.0
  flutter_cache_manager: any
  flutter_html: ^0.11.1
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^2.0.0
  flutter_open_whatsapp: ^0.1.2
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^4.2.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_typeahead: ^3.2.0
  fluttertoast: ^8.0.7
  google_ml_kit: ^0.6.0
  google_sign_in: ^5.0.5
  image: ^3.0.2
  image_picker: ^0.8.2
  in_app_review: ^2.0.2
  intl: ^0.17.0
  jiffy: ^4.1.0
  page_transition: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  rxdart: ^0.27.1
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  stripe_sdk: ^5.0.0-nullsafety.0
  tflite_flutter: ^0.8.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  floor_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon.png
    - assets/user_profile/
    - assets/payment_icon/

  fonts:
    - family: Signika Negative
      fonts:
        - asset: fonts/signika_negative/SignikaNegative-Regular.ttf
        - asset: fonts/signika_negative/SignikaNegative-Bold.ttf
          weight: 700
